CREATE TABLE IF NOT EXISTS slot_snapshots (
    captured_at       DateTime64(3),
    symbol            LowCardinality(String),
    slot_ts           UInt32,
    slot_duration     UInt32,
    minutes_into_slot Float32,
    pct_into_slot     Float32,
    bid_up            Float32,
    ask_up            Float32,
    bid_down          Float32,
    ask_down          Float32,
    bid_size_up       Float32,
    ask_size_up       Float32,
    bid_size_down     Float32,
    ask_size_down     Float32,
    spread_up         Float32,
    spread_down       Float32,
    bid_up_l2         Float32,
    ask_up_l2         Float32,
    bid_up_l3         Float32,
    ask_up_l3         Float32,
    bid_down_l2       Float32,
    ask_down_l2       Float32,
    bid_down_l3       Float32,
    ask_down_l3       Float32,
    mid_up            Float32,
    mid_down          Float32,
    size_ratio_up     Float32,
    size_ratio_down   Float32,
    chainlink_price   Float32,
    dir_move_pct      Float32,
    abs_move_pct      Float32,
    hour_utc          UInt8,
    day_of_week       UInt8,
    market_volume_usd Float32,
    winner            Nullable(Enum8('UP' = 1, 'DOWN' = 2)),
    btc_price_start   Float32,
    btc_price_end     Float32
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(captured_at)
ORDER BY (symbol, slot_duration, captured_at)
SETTINGS index_granularity = 8192;
