export const indicators = [
    { value: 'abs_move_pct', label: 'Abs Move %', category: 'Price' },
    { value: 'dir_move_pct', label: 'Dir Move %', category: 'Price' },
    { value: 'spread_up', label: 'Spread UP', category: 'Spread' },
    { value: 'spread_down', label: 'Spread DOWN', category: 'Spread' },
    { value: 'spread_up_rel', label: 'Spread UP % Mid', category: 'Spread' },
    {
        value: 'spread_down_rel',
        label: 'Spread DOWN % Mid',
        category: 'Spread',
    },
    { value: 'size_ratio_up', label: 'Size Ratio UP', category: 'Order Book' },
    {
        value: 'size_ratio_down',
        label: 'Size Ratio DOWN',
        category: 'Order Book',
    },
    {
        value: 'l1_imbalance_up',
        label: 'L1 Imbalance UP',
        category: 'Order Book',
    },
    {
        value: 'l1_imbalance_down',
        label: 'L1 Imbalance DOWN',
        category: 'Order Book',
    },
    { value: 'cross_sum_mid', label: 'Cross Sum Mid', category: 'Parity' },
    { value: 'cross_sum_bid', label: 'Cross Sum Bid', category: 'Parity' },
    { value: 'cross_sum_ask', label: 'Cross Sum Ask', category: 'Parity' },
    { value: 'parity_gap_up', label: 'Parity Gap UP', category: 'Parity' },
    { value: 'pct_into_slot', label: '% Into Slot', category: 'Time' },
    {
        value: 'minutes_into_slot',
        label: 'Minutes Into Slot',
        category: 'Time',
    },
    { value: 'mid_up', label: 'Mid UP', category: 'Price' },
    { value: 'mid_down', label: 'Mid DOWN', category: 'Price' },
    { value: 'bid_up', label: 'Bid UP', category: 'Order Book' },
    { value: 'ask_up', label: 'Ask UP', category: 'Order Book' },
    { value: 'bid_down', label: 'Bid DOWN', category: 'Order Book' },
    { value: 'ask_down', label: 'Ask DOWN', category: 'Order Book' },
    { value: 'bid_size_up', label: 'Bid Size UP', category: 'Order Book' },
    { value: 'ask_size_up', label: 'Ask Size UP', category: 'Order Book' },
    { value: 'bid_size_down', label: 'Bid Size DOWN', category: 'Order Book' },
    { value: 'ask_size_down', label: 'Ask Size DOWN', category: 'Order Book' },
    { value: 'bid_up_l2', label: 'Bid UP L2', category: 'Order Book' },
    { value: 'ask_up_l2', label: 'Ask UP L2', category: 'Order Book' },
    { value: 'bid_up_l3', label: 'Bid UP L3', category: 'Order Book' },
    { value: 'ask_up_l3', label: 'Ask UP L3', category: 'Order Book' },
    { value: 'bid_down_l2', label: 'Bid DOWN L2', category: 'Order Book' },
    { value: 'ask_down_l2', label: 'Ask DOWN L2', category: 'Order Book' },
    { value: 'bid_down_l3', label: 'Bid DOWN L3', category: 'Order Book' },
    { value: 'ask_down_l3', label: 'Ask DOWN L3', category: 'Order Book' },
    { value: 'bid_gap_up_12', label: 'Bid Gap UP 1-2', category: 'Depth' },
    { value: 'bid_gap_up_23', label: 'Bid Gap UP 2-3', category: 'Depth' },
    { value: 'ask_gap_up_12', label: 'Ask Gap UP 1-2', category: 'Depth' },
    { value: 'ask_gap_up_23', label: 'Ask Gap UP 2-3', category: 'Depth' },
    { value: 'bid_gap_down_12', label: 'Bid Gap DOWN 1-2', category: 'Depth' },
    { value: 'bid_gap_down_23', label: 'Bid Gap DOWN 2-3', category: 'Depth' },
    { value: 'ask_gap_down_12', label: 'Ask Gap DOWN 1-2', category: 'Depth' },
    { value: 'ask_gap_down_23', label: 'Ask Gap DOWN 2-3', category: 'Depth' },
    { value: 'ref_price', label: 'Reference Price', category: 'Price' },
    { value: 'hour_utc', label: 'Hour (UTC)', category: 'Time' },
    { value: 'day_of_week', label: 'Day of Week', category: 'Time' },
    { value: 'market_volume_usd', label: 'Volume (USD)', category: 'Volume' },
] as const;

export const operators = [
    { value: '>', label: '>' },
    { value: '<', label: '<' },
    { value: '>=', label: '>=' },
    { value: '<=', label: '<=' },
    { value: '==', label: '=' },
    { value: '!=', label: '!=' },
    { value: 'between', label: 'Between' },
] as const;
